spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/logistica_reversa
spring.datasource.username=logistica
spring.datasource.password=logistica123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

app.jwt.secret=EzrV/4952oLbTkh3oxjfiJ0pUDN5xpmBb2Q3E16mp74mcX/zi0qZHQG///7MMPQ3MuXbuZvP16DDmh9Y4z3vMg==
app.jwt.expiration-seconds=28800